### PR TITLE
Global limits

### PR DESCRIPTION
**Pull request by thefringeninja**
This PR scopes rate limits per middleware 'instance' rather than per request / response

question: do we want `RateLimiter` scope split for request / response?

### CODE REVIEW

**Comment by damianh** [comment]
I want to support rate limiting per request/response AND per MW instance.

Instead of changing `MaxBandwidth` MW, add a new one `MaxGlobalBandwidth` (or maybe `MaxTotalBandwidth`?). This means we retain compatibility and it's only a minor change semver wise.

**Comment by thefringeninja** [comment]
This is ready for review. No idea why the build is failing; all tests pass and nuget package created properly

**Comment by damianh** [comment]
Yeah no idea why build is failing either....

**Comment by damianh** [comment]
Cheers for this.

Going to rename 'GlobalMaxBandwidth' to `MaxBandwidthGlobal` so it feels symmetrical with `MaxBandwidthPerRequest`

**Comment by thefringeninja** [comment]
Gah! naming things

On Sat, Mar 28, 2015 at 11:21 PM, Damian Hickey <notifications@github.com>
wrote:

> Cheers for this.
>
> Going to rename 'GlobalMaxBandwidth' to MaxBandwidthGlobal so it feels
> symmetrical with MaxBandwidthPerRequest
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/damianh/LimitsMiddleware/pull/17#issuecomment-87323413>
> .
>



-- 
Sent from my regular computer
http://twitter.com/thefringeninja
http://www.thefringeninja.com/

**Pull request merged**
